Homework1 fragments
lleuad0/abbyydevcourse pull request #8
Opened 2020-05-18 11:36 UTC by lleuad0

Перевела список заметок и просмотр с Активити на Фрагменты

2020-05-18 11:57 UTC, IvanShafran commented on Rebbargtxet/app/src/main/java/com/github/lleuad0/rebbargtxet/MainActivity.kt
> +        lateinit var manager: FragmentManager
Не, это зря. Хранить любые View, Context и подобные штуки в static полях/companion методах опасно. Если их не очистить, то они будут висеть в памяти постоянно.
Хранить FragmentManager в обычной переменной тоже нет смысла.

Если нужен FragmentManager и ты знаешь, что по lifecycle он обязательно жив, то можно использовать requireSupportFragmentManager() функцию, если не знаешь жив ли он, то nullable supportFragmentManager
Чуть подробнее про разницу между методами: https://medium.com/@shafran/fragment-getcontext-vs-requirecontext-ffc9157d6bbe

2020-05-18 12:04 UTC, IvanShafran requested changes
Вынесение во Fragment правильно) Нужно только исправить открытие экрана по клику во ViewHolder-е

2020-05-18 12:04 UTC, IvanShafran commented on Rebbargtxet/app/src/main/java/com/github/lleuad0/rebbargtxet/NoteViewHolder.kt
> +            val fragmentNoteContent = FragmentNoteContent()
Я понимаю, почему появилось желание вынести manager в переменную)
Чтобы избежать этого можно объявить слушатель и передать его сюда.
Пример тут: https://github.com/IvanShafran/abbyy-mobile-school-2019/tree/master/RecyclerViewSample/app/src/main/java/me/shafran/rvsample
Смотреть ListActivity, Adapter, ViewHolder.
Идея в том, чтобы информацию о клике передать во Fragment.
Потом из Fragment-а вызвать метод Acitivty уже.
Пример: https://github.com/IvanShafran/note-app/blob/d6044aa0f9c9e7deaf6d3ab03c1723bba1d78b4a/app/src/main/java/com/github/ivanshafran/noteapp/NoteListFragment.kt#L64
https://github.com/IvanShafran/note-app/blob/d6044aa0f9c9e7deaf6d3ab03c1723bba1d78b4a/app/src/main/java/com/github/ivanshafran/noteapp/MainActivity.kt#L37

2020-05-24 16:20 UTC, lleuad0 commented on Rebbargtxet/app/src/main/java/com/github/lleuad0/rebbargtxet/MainActivity.kt
> +        lateinit var manager: FragmentManager
Насколько я поняла, геттер для supportFragmentManager всегда возвращает не-nullable значение. Но companion object и переменную убрала

2020-06-04 11:43 UTC, IvanShafran commented on Rebbargtxet/app/src/main/java/com/github/lleuad0/rebbargtxet/MainActivity.kt
> +        lateinit var manager: FragmentManager
Да, для Activity всегда есть. Для Fragment-а -- нет. Перепутал)

2020-06-04 11:45 UTC, IvanShafran approved these changes
Во, теперь всё корректно)

2020-06-05 15:46 UTC, merged