Добавила разметку для планшетов
lleuad0/abbyydevcourse pull request #9
Opened 2020-07-30 12:09 UTC by lleuad0

Лучше поздно, чем никогда.

2020-08-01 22:12 UTC, IvanShafran requested changes
Всё хорошо, но для простоты давай на планшете две половинки в любой ориентации

2020-08-01 22:12 UTC, IvanShafran commented on Rebbargtxet/app/src/main/java/com/github/lleuad0/rebbargtxet/MainActivity.kt
> +    companion object {
В принципе, их можно сделать методами класса. У Activity тоже можно получит resources. 
Просто если использовать ресурсы из приложения, то логично иметь эти функции вне класса. Как утилитные доступные везде

2020-08-01 22:12 UTC, IvanShafran commented on Rebbargtxet/app/src/main/res/layout-w600dp-land/activity_main.xml
> +<?xml version="1.0" encoding="utf-8"?>
А по заданию только в landscape на планшете нужно в два столбца? Уже не помню)
В любом случае, предлагаю на планшете всегда иметь два столбца(фрагмента в смысле). Будет сильно проще

2020-08-01 22:12 UTC, IvanShafran commented on Rebbargtxet/app/src/main/java/com/github/lleuad0/rebbargtxet/FragmentNoteContent.kt
> +            activity?.findViewById<View>(R.id.fragment_holder_note)?.visibility = View.VISIBLE
Такие вызовы лучше избегать. Фрагмент оперирует знанием того какая верстка у активити. При изменении верстки у Активити придется переделывать и код фрагмента, что не круто)
Думаю, этот метод можно убрать если на планшете всегда иметь две половинки

2020-08-02 16:43 UTC, lleuad0 commented on Rebbargtxet/app/src/main/java/com/github/lleuad0/rebbargtxet/MainActivity.kt
> +    companion object {
Хорошо, поняла) Сейчас, когда на планшетах стал в обеих ориентациях одинаковый дизайн, эти методы вообще оказались не нужны, но на будущее запомню.

2020-08-02 16:44 UTC, lleuad0 commented on Rebbargtxet/app/src/main/java/com/github/lleuad0/rebbargtxet/FragmentNoteContent.kt
> +            activity?.findViewById<View>(R.id.fragment_holder_note)?.visibility = View.VISIBLE
Пересмотрела сейчас дизайн и поняла, что я ещё усложнила себе задачу. Эти if'ы были нужны, чтобы на планшетах в лендскейпе, если заметка не показывается, то список растягивался бы на весь экран. Но на самом деле растягивать было не надо, это я перепутала с планшетом в портрете 🤦‍♀️ 😁

2020-08-02 16:47 UTC, lleuad0 commented on Rebbargtxet/app/src/main/res/layout-w600dp-land/activity_main.xml
> +<?xml version="1.0" encoding="utf-8"?>
Да, по дизайну фрагмент заметки в портрете заменял фрагмент списка, как на телефонах. Но никаких проблем, переделала) Кстати, спасибо ещё раз, что согласился помочь после такого долгого времени.

2020-08-05 18:27 UTC, IvanShafran approved these changes

2020-08-07 09:41 UTC, merged